# Generated by Django 5.0.2 on 2024-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Process'), ('S', 'Success'), ('C', 'Canceled')], default='P', max_length=1, verbose_name='Статус платежа'),
        ),
    ]
